name: Profile

on: [push]

jobs:
    build:
        if: startsWith(github.ref, 'refs/tags/')                                # Only profile on tag pushes.
        runs-on: ubuntu-24.04                                                   # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
        strategy:
            matrix:
                python-version: ["3.11", "3.12", "3.13"]
        steps:
            -
                name: Checkout project
                uses: actions/checkout@v5                                       # https://github.com/actions/checkout
                with:
                    path: main
                    submodules: true
            -
                name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v6                                   # https://github.com/actions/setup-python
                with:
                    cache: pip
                    cache-dependency-path: |
                        main/requirements.txt
                    python-version: ${{ matrix.python-version }}
            -
                name: Install Python dependencies
                run: |
                    sudo apt-get update
                    sudo apt-get install exiftool
                    sudo apt-get install optipng
            -
                name: Install Python ${{ matrix.python-version }} dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r main/requirements.txt
            -
                name: List programs
                run: |
                    echo "::notice $(which exiftool)"
                    echo "::notice $(which optipng)"
                    echo "::notice $(which pip)"
                    echo "::notice $(which python)"
            -
                name : Set up environment for Python
                run : |
                    echo "PYTHONPATH=${PWD}/main:${PYTHONPATH}" >> ${GITHUB_ENV}
                    echo "PYTHONSAFEPATH=aNonEmptyString" >> ${GITHUB_ENV}
            -
                name: Profile the Python ${{ matrix.python-version }} code
                run: |
                    cd main
                    python -m cProfile -o cProfile.log example.py
                    python -c 'import pstats; p = pstats.Stats("cProfile.log"); p.sort_stats(pstats.SortKey.CUMULATIVE).print_stats("fmc/fmc", 25)'
                    python -c 'import pstats; p = pstats.Stats("cProfile.log"); p.sort_stats(pstats.SortKey.CUMULATIVE).print_stats("pyguymer3/pyguymer3", 25)'
